/* Tree TwoSpecimenTree for 16072 generated by http://behaviortrees.ftcteams.com */
        package org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Trees;

import com.ftcteams.behaviortrees.Failover;
import com.ftcteams.behaviortrees.Node;
import com.ftcteams.behaviortrees.Parallel;
import com.ftcteams.behaviortrees.Sequence;

import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ArmToIntake;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ArmToScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToIntakePosition;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToScorePosition;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.FirstScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.MoveForwardForTime;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.Park;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.StandardScore;


public class Cycle {
    public static final int TIMEOUT_SECONDS = 10;

    public static Node root(){
        return new Sequence(
                Intake.root(),
                new MoveForwardForTime(.1,-1),
                new Parallel(2,
                        new DriveToScorePosition(TIMEOUT_SECONDS),
                        new ArmToScore(TIMEOUT_SECONDS)),
                new StandardScore(TIMEOUT_SECONDS),
                new MoveForwardForTime(0.25,1),
                new Parallel(2,
                        new DriveToIntakePosition(TIMEOUT_SECONDS),
                        new ArmToIntake(TIMEOUT_SECONDS)));

    }
}

/* TREE
?
|  ->
|  |  [FisrtScore]
|  |  [DriveToIntakePosition]
|  |  [Intake]
|  |  [DrivetoScorePosition]
|  |  [StandardScore]
|  |  [Park]
|  [Park]
 */