package org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Trees;

/* Tree PreloadAuto for 16072 generated by http://behaviortrees.ftcteams.com */

import com.ftcteams.behaviortrees.Node;
import com.ftcteams.behaviortrees.Sequence;

import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToFirstSample;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToSamples;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToSecondSample;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.PushFirstSample;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.PushSecondSample;


public class PushSamples {

    public static final int TIMEOUT_SECONDS = 10;

    public static Node root() {
        return new Sequence(
                new DriveToSamples(TIMEOUT_SECONDS),
                new DriveToFirstSample(TIMEOUT_SECONDS),
                new PushFirstSample(TIMEOUT_SECONDS),
                new DriveToFirstSample(TIMEOUT_SECONDS),
                new DriveToSecondSample(TIMEOUT_SECONDS),
                new PushSecondSample(TIMEOUT_SECONDS));
    }
}

/* TREE
?
|  ->
|  |  [DriveToChamber]
|  |  [Score]
|  |  [Park]
|  [Park]
 */
