package org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Trees;

/* Tree PreloadAuto for 16072 generated by http://behaviortrees.ftcteams.com */

import com.ftcteams.behaviortrees.Failover;
import com.ftcteams.behaviortrees.Node;
import com.ftcteams.behaviortrees.Parallel;
import com.ftcteams.behaviortrees.Sequence;

import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ArmToIntake;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ArmToScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.BehindChamber;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.BehindChamberForSecondScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.BehindChamberForThirdScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToChamber;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToFirstSample;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToSamples;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.GetReadyToPushSamples;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.Park;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ReadyToIntakeOne;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ScoreClawOpen;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.WaitForClawOpen;


public class TestAutoTree {

    public static final int TIMEOUT_SECONDS = 10;

    public static Node root(){
        return new Sequence(
                new Park(TIMEOUT_SECONDS));
}}


