/* Tree TwoSpecimenTree for 16072 generated by http://behaviortrees.ftcteams.com */
        package org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Trees;

import com.ftcteams.behaviortrees.Node;
import com.ftcteams.behaviortrees.Failover;
import com.ftcteams.behaviortrees.Sequence;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.FirstScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToIntakePosition;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.Intake;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DrivetoScorePosition;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.StandardScore;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.Park;


public class TwoSpecimenTree {
    public static final int TIMEOUT_SECONDS = 5;

    public static Node root(){
        return new Failover(
                new Sequence(
                        new FirstScore(TIMEOUT_SECONDS),
                        new DriveToIntakePosition(),
                        Intake.root(),
                        new DrivetoScorePosition(),
                        new StandardScore(TIMEOUT_SECONDS),
                        new Park(TIMEOUT_SECONDS)),
                new Park(TIMEOUT_SECONDS));
    }
}

/* TREE
?
|  ->
|  |  [FisrtScore]
|  |  [DriveToIntakePosition]
|  |  [Intake]
|  |  [DrivetoScorePosition]
|  |  [StandardScore]
|  |  [Park]
|  [Park]
 */