/* Tree SpecSampleParkAuto for 16072 generated by http://behaviortrees.ftcteams.com */
package org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Trees;

import com.ftcteams.behaviortrees.Node;
import com.ftcteams.behaviortrees.Failover;
import com.ftcteams.behaviortrees.Sequence;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToSub;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.PlaceSpecimen;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.StrafeToMarker;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.PickUpSample;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.DriveToObservationDeck;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.ReleaseSample;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.Wait;
import org.firstinspires.ftc.teamcode.ftc16072.BehaviorTrees.Actions.Park;


public class SpecSampleParkTree {
    public static Node root(){
        return new Failover(
                new Sequence(
                        new DriveToSub(),
                        new PlaceSpecimen(),
                        new StrafeToMarker(),
                        new PickUpSample(),
                        new DriveToObservationDeck(),
                        new ReleaseSample(),
                        new Wait(),
                        new Park()),
                new Park());
    }
}

/* TREE
?
|  ->
|  |  [GoToSub]
|  |  [PlaceSpecimen]
|  |  [StrafeToMarker]
|  |  [PickUpSample]
|  |  [DriveToObservationDeck]
|  |  [ReleaseSample]
|  |  [Wait]
|  |  [Park]
|  [Park]
 */